name = "passkey-auth-service"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "authservice.sanjaysingh.net", custom_domain = true }
]

[vars]
RP_ID = "sanjaysingh.net"
RP_NAME = "sanjaysingh.net auth service"
ORIGIN = "https://sanjaysingh.net"

# Secrets should be set using: wrangler secret put JWT_SECRET
# JWT_SECRET will be injected as an environment variable

# KV namespace will be added during deployment 
[[kv_namespaces]]
binding = "AUTH_KV"
id = "06d30ff8c8394e3e88424bb190f395c4" 

[observability]
enabled = true